"""create core account tables

Revision ID: 49e5c01e7c6c
Revises: ad77297002e7
Create Date: 2026-04-24 15:26:01.185984
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49e5c01e7c6c"
down_revision: str | None = "ad77297002e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role_code",
            sa.Enum(
                "platform_admin",
                "counselor",
                "advisor",
                name="admin_role_code_enum",
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "last_login_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_users_username")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "student_users",
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("wechat_openid", sa.String(length=64), nullable=True),
        sa.Column("display_nickname", sa.String(length=32), nullable=False),
        sa.Column("display_avatar_seed", sa.String(length=64), nullable=False),
        sa.Column("college_name", sa.String(length=64), nullable=False),
        sa.Column("class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "risk_status",
            sa.Enum(
                "normal",
                "watch",
                "high",
                name="student_risk_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "consent_status",
            sa.Enum(
                "granted",
                "declined",
                "missing",
                name="student_consent_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "last_login_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_users")),
        sa.UniqueConstraint("phone_e164", name=op.f("uq_student_users_phone_e164")),
        sa.UniqueConstraint("wechat_openid", name=op.f("uq_student_users_wechat_openid")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "consent_records",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "consent_type",
            sa.Enum(
                "privacy_policy",
                "crisis_intervention_authorization",
                name="consent_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("consent_version", sa.String(length=16), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_consent_records_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consent_records")
    op.drop_table("student_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
