"""create review and audit tables

Revision ID: 5295854b6475
Revises: 84d79874b9ff
Create Date: 2026-04-25 11:52:29.032318
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5295854b6475"
down_revision: str | None = "84d79874b9ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "actor_type",
            sa.Enum("student", "admin", "system", name="audit_actor_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "actor_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.Column("action_code", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column(
            "target_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "focus_list_entries",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("treehole", "assessment", "history", name="focus_source_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "source_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "resolved", name="focus_list_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_focus_list_entries_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_focus_list_entries")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "alert_cases",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("treehole", "assessment", "history", name="case_source_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "source_post_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "source_submission_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "case_level",
            sa.Enum("watch", "high", name="alert_case_level_enum"),
            nullable=False,
        ),
        sa.Column(
            "queue_status",
            sa.Enum(
                "pending_review",
                "confirmed_pending_intervention",
                "dismissed_false_positive",
                "closed",
                name="alert_queue_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_priority",
            sa.Enum("normal", "urgent", "highest", name="review_priority_enum"),
            nullable=False,
        ),
        sa.Column("ai_reason_text", sa.Text(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "reviewed_by",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column("simulated_notice_log", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["admin_users.id"],
            name=op.f("fk_alert_cases_reviewed_by_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_post_id"],
            ["treehole_posts.id"],
            name=op.f("fk_alert_cases_source_post_id_treehole_posts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_submission_id"],
            ["questionnaire_submissions.id"],
            name=op.f("fk_alert_cases_source_submission_id_questionnaire_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_alert_cases_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_cases")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "intervention_logs",
        sa.Column(
            "alert_case_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "admin_user_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sa.Enum(
                "confirm_high_risk",
                "dismiss_false_positive",
                "simulate_contact",
                "add_note",
                "close_case",
                name="intervention_action_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("action_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_intervention_logs_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["alert_case_id"],
            ["alert_cases.id"],
            name=op.f("fk_intervention_logs_alert_case_id_alert_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intervention_logs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intervention_logs")
    op.drop_table("alert_cases")
    op.drop_table("focus_list_entries")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
