"""create questionnaire tables

Revision ID: 7570a1e0c36e
Revises: 49e5c01e7c6c
Create Date: 2026-04-24 16:13:58.978843
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7570a1e0c36e"
down_revision: str | None = "49e5c01e7c6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnaire_templates",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "category",
            sa.Enum("required", "optional", name="questionnaire_category_enum"),
            nullable=False,
        ),
        sa.Column(
            "question_count",
            sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "scoring_mode",
            sa.Enum(
                "sum_1_5",
                "sum_0_3",
                "zung_standard",
                "yes_no",
                name="questionnaire_scoring_mode_enum",
            ),
            nullable=False,
        ),
        sa.Column("unlock_required", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_templates")),
        sa.UniqueConstraint("code", name=op.f("uq_questionnaire_templates_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "assessment_reports",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.Enum(
                "scale_result",
                "full_profile",
                name="assessment_report_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("report_version", sa.String(length=16), nullable=False),
        sa.Column("source_submission_ids_json", sa.JSON(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("low", "watch", "high", name="assessment_report_risk_level_enum"),
            nullable=False,
        ),
        sa.Column("result_title", sa.String(length=128), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_assessment_reports_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_reports")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "question_bank",
        sa.Column(
            "template_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column("question_code", sa.String(length=32), nullable=False),
        sa.Column(
            "question_order",
            sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum("single_choice", "yes_no", name="question_type_enum"),
            nullable=False,
        ),
        sa.Column("options_json", sa.JSON(), nullable=False),
        sa.Column("score_mapping_json", sa.JSON(), nullable=False),
        sa.Column("reverse_scored", sa.Boolean(), nullable=False),
        sa.Column("hard_trigger_rule_json", sa.JSON(), nullable=True),
        sa.Column("seed_source", sa.String(length=128), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["questionnaire_templates.id"],
            name=op.f("fk_question_bank_template_id_questionnaire_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank")),
        sa.UniqueConstraint("question_code", name=op.f("uq_question_bank_question_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "questionnaire_submissions",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "template_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "scored",
                name="questionnaire_submission_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("raw_score", sa.Integer(), nullable=False),
        sa.Column("standardized_score", sa.Integer(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum("low", "watch", "high", name="questionnaire_risk_level_enum"),
            nullable=False,
        ),
        sa.Column("hard_trigger_hit", sa.Boolean(), nullable=False),
        sa.Column("scoring_snapshot_json", sa.JSON(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_questionnaire_submissions_student_id_student_users"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["questionnaire_templates.id"],
            name=op.f("fk_questionnaire_submissions_template_id_questionnaire_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_submissions")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "questionnaire_answers",
        sa.Column(
            "submission_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "question_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column("selected_option", sa.String(length=32), nullable=False),
        sa.Column("raw_value", sa.String(length=32), nullable=False),
        sa.Column("normalized_score", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
            name=op.f("fk_questionnaire_answers_question_id_question_bank"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["questionnaire_submissions.id"],
            name=op.f("fk_questionnaire_answers_submission_id_questionnaire_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_answers")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questionnaire_answers")
    op.drop_table("questionnaire_submissions")
    op.drop_table("question_bank")
    op.drop_table("assessment_reports")
    op.drop_table("questionnaire_templates")
    # ### end Alembic commands ###
