"""create treehole tables

Revision ID: 84d79874b9ff
Revises: 7570a1e0c36e
Create Date: 2026-04-25 11:40:15.996283
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "84d79874b9ff"
down_revision: str | None = "7570a1e0c36e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "treehole_posts",
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column("anonymous_name", sa.String(length=64), nullable=False),
        sa.Column("anonymous_avatar_key", sa.String(length=64), nullable=False),
        sa.Column(
            "content_raw",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "content_masked",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "ai_status",
            sa.Enum(
                "pending",
                "analyzed",
                "mocked",
                "failed",
                name="treehole_ai_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "publish_status",
            sa.Enum(
                "pending_review",
                "published",
                "blocked_high_risk",
                "deleted_by_user",
                "hidden_by_admin",
                name="treehole_publish_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum("low", "watch", "high", name="treehole_risk_level_enum"),
            nullable=False,
        ),
        sa.Column("allow_publication", sa.Boolean(), nullable=False),
        sa.Column(
            "hug_count",
            sa.Integer().with_variant(mysql.INTEGER(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "published_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_treehole_posts_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treehole_posts")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "ai_analysis_records",
        sa.Column(
            "target_type",
            sa.Enum("treehole_post", name="ai_analysis_target_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "target_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum("deepseek", name="ai_analysis_provider_enum"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("request_payload_json", sa.JSON(), nullable=False),
        sa.Column("response_raw_json", sa.JSON(), nullable=True),
        sa.Column(
            "parsed_risk_level",
            sa.Enum("low", "watch", "high", name="ai_analysis_risk_level_enum"),
            nullable=False,
        ),
        sa.Column(
            "parsed_risk_score", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("emotion_tags_json", sa.JSON(), nullable=False),
        sa.Column("trigger_phrases_json", sa.JSON(), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column(
            "recommended_action",
            sa.Enum(
                "publish",
                "focus_list",
                "manual_review_high",
                name="ai_recommended_action_enum",
            ),
            nullable=False,
        ),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["treehole_posts.id"],
            name=op.f("fk_ai_analysis_records_target_id_treehole_posts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analysis_records")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_table(
        "post_reactions",
        sa.Column(
            "post_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "student_id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "reaction_type",
            sa.Enum("hug", "light", "accompany", name="post_reaction_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Integer().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["treehole_posts.id"],
            name=op.f("fk_post_reactions_post_id_treehole_posts"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_users.id"],
            name=op.f("fk_post_reactions_student_id_student_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_reactions")),
        sa.UniqueConstraint(
            "post_id",
            "student_id",
            "reaction_type",
            name="uq_post_reactions_post_id_student_id_reaction_type",
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_reactions")
    op.drop_table("ai_analysis_records")
    op.drop_table("treehole_posts")
    # ### end Alembic commands ###
